model_path : "./palm_edge_2.0.4_tnn.pbz"
compute_configs {
    model_name: "palm_detection@baseline9_yolox_100m_relu_exp21_eval127"
    device_type: DeviceArm
    thread_num: 4
    cpu_list: 0
    cpu_list: 1
    cpu_list: 2
    cpu_list: 3
}
compute_configs {
    model_name: "palm_regression@baseline4_mnv4_nano_exp4_eval404"
    device_type: DeviceArm
    thread_num: 4
    cpu_list: 0
    cpu_list: 1
    cpu_list: 2
    cpu_list: 3
}
compute_configs {
    model_name: "palman_kps@exp30_checkpoint_937"
    device_type: DeviceArm
    thread_num: 4
    cpu_list: 0
    cpu_list: 1
    cpu_list: 2
    cpu_list: 3
}

compute_configs {
    model_name: "palm_liveness@rgb_color_gray_exp22_3662@wq5008"
    device_type: DeviceArm
    thread_num: 4
    cpu_list: 0
    cpu_list: 1
    cpu_list: 2
    cpu_list: 3
}
compute_configs {
    model_name: "palm_reliability@rgb_baseline13_exp17_eval32"
    device_type: DeviceArm
    thread_num: 4
    cpu_list: 0
    cpu_list: 1
    cpu_list: 2
    cpu_list: 3
}
compute_configs {
    model_name: "palm_reliability_register@rgb_baseline5_exp5_eval71"
    device_type: DeviceArm
    thread_num: 4
    cpu_list: 0
    cpu_list: 1
    cpu_list: 2
    cpu_list: 3
}
compute_configs {
    model_name: "palm_phone_quality_register@exp32_eval_1095_backbone"
    device_type: DeviceArm
    thread_num: 4
    cpu_list: 0
    cpu_list: 1
    cpu_list: 2
    cpu_list: 3
}
compute_configs {
    model_name: "palm_phone_register_reliability@baseline26_eval_14"
    device_type: DeviceArm
    thread_num: 4
    cpu_list: 0
    cpu_list: 1
    cpu_list: 2
    cpu_list: 3
}
compute_configs {
    model_name: "palm_recognition@rgb_mbf_exp6_draw@0.98728_0.75941@rank_0_eval_136_backbone"
    device_type: DeviceArm
    thread_num: 4
    cpu_list: 0
    cpu_list: 1
    cpu_list: 2
    cpu_list: 3
}